module.exports = {
  content: [
    './**/*.php',
    './tailwind.safelist.txt',
  ],
  important: true,
  theme: {
    extend: {
      textColor: {
        'base-color': 'var(--wp--custom--site--text-color)',
      },
      borderWidth: {
        '3': '3px',
      },
      backgroundColor: {
        overlay: 'var(--wp--custom--color--overlay)',
      },
      colors: {
        black: 'var(--wp--custom--color--black)',
        white: 'var(--wp--custom--color--white)',
        gray: {
          '50': 'var(--wp--custom--color--gray-50)',
          '100': 'var(--wp--custom--color--gray-100)',
          '200': 'var(--wp--custom--color--gray-200)',
          '300': 'var(--wp--custom--color--gray-300)',
          '400': 'var(--wp--custom--color--gray-400)',
          '500': 'var(--wp--custom--color--gray-500)',
          '600': 'var(--wp--custom--color--gray-600)',
          '700': 'var(--wp--custom--color--gray-700)',
          '800': 'var(--wp--custom--color--gray-800)',
          '900': 'var(--wp--custom--color--gray-900)',
        },
        primary: {
          '50': 'var(--wp--custom--color--primary-50)',
          '100': 'var(--wp--custom--color--primary-100)',
          '200': 'var(--wp--custom--color--primary-200)',
          '300': 'var(--wp--custom--color--primary-300)',
          '400': 'var(--wp--custom--color--primary-400)',
          '500': 'var(--wp--custom--color--primary-500)',
          '600': 'var(--wp--custom--color--primary-600)',
          '700': 'var(--wp--custom--color--primary-700)',
          '800': 'var(--wp--custom--color--primary-800)',
          '900': 'var(--wp--custom--color--primary-900)',
        },
        secondary: {
          '50': 'var(--wp--custom--color--secondary-50)',
          '100': 'var(--wp--custom--color--secondary-100)',
          '200': 'var(--wp--custom--color--secondary-200)',
          '300': 'var(--wp--custom--color--secondary-300)',
          '400': 'var(--wp--custom--color--secondary-400)',
          '500': 'var(--wp--custom--color--secondary-500)',
          '600': 'var(--wp--custom--color--secondary-600)',
          '700': 'var(--wp--custom--color--secondary-700)',
          '800': 'var(--wp--custom--color--secondary-800)',
          '900': 'var(--wp--custom--color--secondary-900)',
        }
      },
      spacing: {
        // container: 'var(--wp--custom--container--padding)',
        // section: 'var(--wp--custom--section--padding)',
        // block: 'var(--wp--custom--blocks--vertical-space)',
        px: 'var(--wp--custom--space--px)',
        0.5: 'var(--wp--custom--space--0-5)',
        1: 'var(--wp--custom--space--1)',
        1.5: 'var(--wp--custom--space--1-5)',
        2: 'var(--wp--custom--space--2)',
        2.5: 'var(--wp--custom--space--2-5)',
        3: 'var(--wp--custom--space--3)',
        3.5: 'var(--wp--custom--space--3-5)',
        4: 'var(--wp--custom--space--4)',
        5: 'var(--wp--custom--space--5)',
        6: 'var(--wp--custom--space--6)',
        7: 'var(--wp--custom--space--7)',
        8: 'var(--wp--custom--space--8)',
        9: 'var(--wp--custom--space--9)',
        10: 'var(--wp--custom--space--10)',
        11: 'var(--wp--custom--space--11)',
        12: 'var(--wp--custom--space--12)',
        14: 'var(--wp--custom--space--14)',
        16: 'var(--wp--custom--space--16)',
        20: 'var(--wp--custom--space--20)',
        24: 'var(--wp--custom--space--24)',
        28: 'var(--wp--custom--space--28)',
        32: 'var(--wp--custom--space--32)',
        36: 'var(--wp--custom--space--36)',
        40: 'var(--wp--custom--space--40)',
        44: 'var(--wp--custom--space--44)',
        48: 'var(--wp--custom--space--48)',
        52: 'var(--wp--custom--space--52)',
        56: 'var(--wp--custom--space--56)',
        60: 'var(--wp--custom--space--60)',
        64: 'var(--wp--custom--space--64)',
        72: 'var(--wp--custom--space--72)',
        80: 'var(--wp--custom--space--80)',
        96: 'var(--wp--custom--space--96)',
      },
    },
    fontFamily: {
      primary: 'var(--wp--custom--site--font-family)',
      secondary: 'var(--wp--custom--site--font-family--secondary)',
      sans: 'var(--wp--custom--site--font-family--sans)',
      serif: 'var(--wp--custom--site--font-family--serif)',
      mono: 'var(--wp--custom--site--font-family--mono)',
    },
    fontSize: {
      'xs': [ 'var(--wp--custom--font-size--xs)', { lineHeight: 'var(--wp--custom--line-height--4)' } ],
      'sm': [ 'var(--wp--custom--font-size--sm)', { lineHeight: 'var(--wp--custom--line-height--5)' } ],
      'base': [ 'var(--wp--custom--font-size--base)', { lineHeight: 'var(--wp--custom--site--line-height)' } ],
      'lg': [ 'var(--wp--custom--font-size--lg)', { lineHeight: 'var(--wp--custom--line-height--7)' } ],
      'xl': [ 'var(--wp--custom--font-size--xl)', { lineHeight: 'var(--wp--custom--line-height--7)' } ],
      '2xl': [ 'var(--wp--custom--font-size--2xl)', { lineHeight: 'var(--wp--custom--line-height--8)' } ],
      '3xl': [ 'var(--wp--custom--font-size--3xl)', { lineHeight: 'var(--wp--custom--line-height--9)' } ],
      '4xl': [ 'var(--wp--custom--font-size--4xl)', { lineHeight: 'var(--wp--custom--line-height--10)' } ],
      '5xl': [ 'var(--wp--custom--font-size--5xl)', { lineHeight: 'var(--wp--custom--line-height--none)' } ],
      '6xl': [ 'var(--wp--custom--font-size--6xl)', { lineHeight: 'var(--wp--custom--line-height--none)' } ],
      '7xl': [ 'var(--wp--custom--font-size--7xl)', { lineHeight: 'var(--wp--custom--line-height--none)' } ],
      '8xl': [ 'var(--wp--custom--font-size--8xl)', { lineHeight: 'var(--wp--custom--line-height--none)' } ],
      '9xl': [ 'var(--wp--custom--font-size--9xl)', { lineHeight: 'var(--wp--custom--line-height--none)' } ],
    },
    lineHeight: {
      '3': 'var(--wp--custom--line-height--3)',
      '4': 'var(--wp--custom--line-height--4)',
      '5': 'var(--wp--custom--line-height--5)',
      '6': 'var(--wp--custom--line-height--6)',
      '7': 'var(--wp--custom--line-height--7)',
      '8': 'var(--wp--custom--line-height--8)',
      '9': 'var(--wp--custom--line-height--9)',
      '10': 'var(--wp--custom--line-height--10)',
      none: 'var(--wp--custom--line-height--none)',
      tight: 'var(--wp--custom--line-height--tight)',
      snug: 'var(--wp--custom--line-height--snug)',
      normal: 'var(--wp--custom--line-height--normal)',
      relaxed: 'var(--wp--custom--line-height--relaxed)',
      loose: 'var(--wp--custom--line-height--loose)',
    },
  },
  corePlugins: {
    container: false,
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
    function ({ addVariant }) {
      addVariant('children', '& > *')
    },
  ],
}
